eureka:
  client:
    service-url:
      defaultZone: http://${eureka.client.service-url.credentials}@localhost:8761/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"